// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: cuisines.sql

package database

import (
	"context"
)

const listCuisines = `-- name: ListCuisines :many
SELECT id, created_at, updated_at, name, parent_id
FROM cuisines
ORDER BY name
`

func (q *Queries) ListCuisines(ctx context.Context) ([]Cuisine, error) {
	rows, err := q.db.Query(ctx, listCuisines)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cuisine
	for rows.Next() {
		var i Cuisine
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.ParentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
