// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: recipe_ingredient.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type AddIngredientsToRecipeParams struct {
	Amount       string    `json:"amount"`
	PrepNote     *string   `json:"prep_note"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	IngredientID uuid.UUID `json:"ingredient_id"`
	RecipeID     uuid.UUID `json:"recipe_id"`
}

const listIngredientsByRecipeID = `-- name: ListIngredientsByRecipeID :many
SELECT
  id,
  name,
  amount,
  prep_note,
  recipe_id
FROM ingredients
JOIN recipe_ingredient ON id = ingredient_id
WHERE recipe_id = $1
`

type ListIngredientsByRecipeIDRow struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	Amount   string    `json:"amount"`
	PrepNote *string   `json:"prep_note"`
	RecipeID uuid.UUID `json:"recipe_id"`
}

func (q *Queries) ListIngredientsByRecipeID(ctx context.Context, recipeID uuid.UUID) ([]ListIngredientsByRecipeIDRow, error) {
	rows, err := q.db.Query(ctx, listIngredientsByRecipeID, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIngredientsByRecipeIDRow
	for rows.Next() {
		var i ListIngredientsByRecipeIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Amount,
			&i.PrepNote,
			&i.RecipeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIngredientInRecipe = `-- name: UpdateIngredientInRecipe :exec
UPDATE recipe_ingredient
SET
  amount = $1,
  prep_note = $2,
  updated_at = $3
WHERE
  ingredient_id = $4 AND recipe_id = $5
`

type UpdateIngredientInRecipeParams struct {
	Amount       string    `json:"amount"`
	PrepNote     *string   `json:"prep_note"`
	UpdatedAt    time.Time `json:"updated_at"`
	IngredientID uuid.UUID `json:"ingredient_id"`
	RecipeID     uuid.UUID `json:"recipe_id"`
}

func (q *Queries) UpdateIngredientInRecipe(ctx context.Context, arg UpdateIngredientInRecipeParams) error {
	_, err := q.db.Exec(ctx, updateIngredientInRecipe,
		arg.Amount,
		arg.PrepNote,
		arg.UpdatedAt,
		arg.IngredientID,
		arg.RecipeID,
	)
	return err
}
