name: ci

on:
  pull_request:
    branches: [main]

env:
  DATABASE_URL: postgres://testuser:testpassword@localhost:5432/testdb?sslmode=disable
  JWT_SECRET: xoEuGejzRwfkgr26Qq3oLZh6vFwaJbGvC2xzlJj8R3+w9WmV9kTiT1rKDyov89lf+OreU3kCTEbict7dsSNKAA==
  PORT: 8080

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
        options: >-
          --health-cmd="pg_isready -U testuser"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Build app
        run: make build/prod

      - name: Run the application
        run: ./bin/planner_server &

      - name: Run db migration
        run: make migrate/up

      - name: Populate the database with cuisines
        run: |
          cd scripts/populate_cuisines
          go build -o bin/populate_cuisines populate_cuisines.go
          ./bin/populate_cuisines

      - name: Run Integration Tests
        run: |
          curl --location --remote-name https://github.com/Orange-OpenSource/hurl/releases/download/4.3.0/hurl_4.3.0_amd64.deb
          sudo dpkg -i hurl_4.3.0_amd64.deb
          hurl --test --variables-file tests/integration/vars.env --glob "tests/integration/**/*.hurl"

  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Run formatter
        run: test -z $(go fmt ./...)

      - name: Run go vet
        run: go vet ./...

      - name: Run staticcheck
        run: go run honnef.co/go/tools/cmd/staticcheck@latest -checks=all,-ST1000,-U1000 ./...

  security:
    name: Security
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Govulncheck
        run: go run golang.org/x/vuln/cmd/govulncheck@latest ./...

      - name: Gosec
        run: go run github.com/securego/gosec/v2/cmd/gosec@latest -exclude-generated -exclude-dir=scripts ./...
